name: Checkmarx One Scan
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
      #  uses: Checkmarx/ast-github-action@2.0.20
        with:
#          project_name: ${{ github.repository }}
          base_uri: ${{ secrets.INPUT_BASE_URI }}
          cx_tenant: ${{ secrets.INPUT_CX_TENANT_ID }}
          cx_client_id: ${{ secrets.INPUT_CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.INPUT_CX_CLIENT_SECRET }}
