name: Checkmarx One Scan
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
      #  uses: Checkmarx/ast-github-action@2.0.20
        with:
#          project_name: ${{ github.repository }}
          base_uri: https://ast.checkmarx.net
          cx_tenant: 14a17e0a-a3a3-48e4-b645-d79feede89ff
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
